name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build README
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get build container
      id: adocbuild
      uses: avattathil/asciidoctor-action@master
      with:
        program: |
          asciidoctor -D docs --backend=html5 *.adoc && mv docs/{README,index}.html

    - name: Deploy docs to ghpages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./docs
